begin;
create table public.profiles(id uuid primary key references auth.users(id),name text not null,role text not null check(role in ('admin','colaborador')));
create function public.is_staff() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid())$$;
create function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;
revoke all on function public.is_staff(),public.is_admin() from public;
grant execute on function public.is_staff(),public.is_admin() to authenticated;
create table public.services(id text primary key,data jsonb not null,version integer not null default 1,check(jsonb_typeof(data->'precio_publico')='number'),check((data->>'precio_publico')::numeric>=0),check(data->>'status' in ('confirmar','autorizado','diagnostico')),check(length(trim(data->>'modelo'))>0),check(length(trim(data->>'servicio'))>0));
create index services_model on public.services(lower(data->>'modelo'));
create table public.charges(id uuid primary key default gen_random_uuid(),service_id text not null references public.services(id),user_id uuid not null references public.profiles(id),branch text not null check(branch in ('Izamal','Buctzotz')),quoted numeric(12,2) not null check(quoted>=0),paid numeric(12,2) not null check(paid>=0),note text,snapshot jsonb not null,created_at timestamptz not null default now());
create index charges_service_date on public.charges(service_id,created_at desc);
create table public.quotes(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id),branch text not null check(branch in ('Izamal','Buctzotz')),message text not null,created_at timestamptz not null default now());
create table public.audit(id bigint generated always as identity primary key,service_id text not null,actor uuid,before jsonb,after jsonb,created_at timestamptz not null default now());
create function public.audit_service() returns trigger language plpgsql security definer set search_path='' as $$begin
 if new.data->>'status'='autorizado' and ((new.data->>'precio_publico')::numeric<=0 or nullif(new.data->>'ultima_actualizacion','') is null or (new.data->>'ultima_actualizacion')::date>current_date or (new.data->>'ultima_actualizacion')::date<current_date-90) then raise exception 'Precio o fecha de autorización inválidos'; end if;
 if tg_op='UPDATE' then new.version=old.version+1;end if;
 insert into public.audit(service_id,actor,before,after) values(new.id,auth.uid(),case when tg_op='UPDATE' then old.data else null end,new.data);return new;end$$;
revoke all on function public.audit_service() from public;
create trigger service_audit before insert or update on public.services for each row execute function public.audit_service();
alter table public.profiles enable row level security;alter table public.services enable row level security;alter table public.charges enable row level security;alter table public.quotes enable row level security;alter table public.audit enable row level security;
revoke all on public.profiles,public.services,public.charges,public.quotes,public.audit from anon,authenticated;
grant select on public.profiles,public.services,public.charges,public.quotes,public.audit to authenticated;
grant insert,update on public.services to authenticated;
grant insert on public.charges,public.quotes to authenticated;
create policy profile_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy services_read on public.services for select to authenticated using(public.is_staff());
create policy services_add on public.services for insert to authenticated with check(public.is_admin());
create policy services_edit on public.services for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy charges_read on public.charges for select to authenticated using(public.is_admin() or user_id=auth.uid());
create policy charges_add on public.charges for insert to authenticated with check(public.is_staff() and user_id=auth.uid());
create policy quotes_read on public.quotes for select to authenticated using(public.is_admin() or user_id=auth.uid());
create policy quotes_add on public.quotes for insert to authenticated with check(public.is_staff() and user_id=auth.uid());
create policy audit_read on public.audit for select to authenticated using(public.is_admin());
commit;
