import {resultsHTML} from './view.js';
import config from './config.js';import {groups,key,title,state,money,quote,norm} from './core.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[],session=null,profile=null,selected=null,cart=[],tab='cotizar',busy=false,resultLimit=12;
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',5000)}
async function api(path,method='GET',body){const r=await fetch(config.url+path,{method,headers:{apikey:config.anon,Authorization:`Bearer ${session?.access_token||config.anon}`,'Content-Type':'application/json',Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json().catch(()=>null);if(!r.ok)throw Error(r.status===401?'Sesión vencida. Vuelve a acceder.':data?.message||data?.error_description||'No se pudo guardar. Revisa tu conexión y permisos.');return data;}
const db=(path,method,body)=>api('/rest/v1/'+path,method,body);
function modal(html){$('#modal-content').innerHTML=html;$('#modal').showModal();}$('#close').onclick=()=>$('#modal').close();
const field=(name,label,value='',type='text',required=true)=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?'min="0" step="0.01"':''}></label>`;
async function saveAction(f){if(busy)return;busy=true;try{await f();$('#modal').close();toast('Guardado correctamente');await load();}catch(e){toast(e.message)}finally{busy=false}}
async function load(){try{if(config.url){if(!session){rows=[];$('#connection').textContent='Acceso del equipo';$('#notice').textContent='Inicia sesión para consultar el catálogo compartido.';render();return;}let all=[];for(let offset=0;;offset+=500){const page=await db(`services?select=*&order=id&limit=500&offset=${offset}`);all.push(...page);if(page.length<500)break;}rows=all.map(r=>({...r.data,service_id:r.id,version:r.version}));$('#connection').textContent=`Conectado · ${profile?.name||'Colaborador'}`;$('#notice').textContent='';}else{rows=await fetch('./catalogo.json').then(r=>r.json());$('#connection').textContent='Modo consulta';$('#notice').textContent='Catálogo histórico: no hay base de datos conectada. No se guardan cambios ni cobros. Configura Supabase para habilitar el trabajo compartido.';}cart=cart.filter(id=>rows.some(s=>s.service_id===id&&s.active!==false&&state(s)==='autorizado'));render();}catch(e){rows=[];cart=[];$('#notice').textContent='No se pudo cargar el catálogo. No se muestran precios almacenados como vigentes.';render();toast(e.message)}}
function basket(){ $('#quote').hidden=!cart.length; $('.workspace').classList.toggle('has-quote',!!cart.length); const items=rows.filter(s=>cart.includes(s.service_id));$('#basket').innerHTML=items.length?items.map(s=>`<div class="basket-item"><strong>${esc(title(s))}</strong><p>${esc(s.servicio)} · ${esc(s.calidad)}</p>${money(s.precio_publico)} <button data-remove="${esc(s.service_id)}">Quitar</button></div>`).join('')+`<div class="total"><strong>Total</strong><strong>${money(items.reduce((a,s)=>a+s.precio_publico,0))}</strong></div>`:'<p class="muted">Selecciona un servicio autorizado para preparar la respuesta.</p>';$('#copy').disabled=$('#whatsapp').disabled=!items.length;}
function render(){
basket();$('#search-panel').hidden=tab==='historial';
if(tab==='historial'){history();return;}
if(config.url&&!session){$('#results').innerHTML='<div class="empty login-empty"><h2>Los precios de MovilPhone, en un solo lugar.</h2><p>Accede con tu cuenta para consultar servicios y precios.</p><button id="login-action" class="primary">Entrar al catálogo</button></div>';return;}
if(tab==='admin'&&profile?.role!=='admin'){$('#results').innerHTML='<div class="empty">Accede como administrador para modificar los precios generales.</div>';return;}
$('#results').innerHTML=resultsHTML(rows,{query:$('#search').value,selected,tab,admin:profile?.role==='admin',signedIn:!!session,cart,limit:resultLimit});
}
function login(){if(session){modal(`<h2>Mi cuenta</h2><p>${esc(profile?.name)} · ${esc(profile?.role)}</p><button id="logout">Cerrar sesión</button>`);$('#logout').onclick=()=>{session=null;profile=null;cart=[];$('#modal').close();$('#account').textContent='Acceder';load()};return;}if(!config.url){modal('<h2>Activa el guardado compartido</h2><p>Configura SUPABASE_URL y SUPABASE_ANON_KEY en Vercel, ejecuta los dos archivos SQL incluidos y vuelve a desplegar. El README explica cómo crear al administrador.</p>');return;}modal(`<h2>Acceso del equipo</h2><form id="login">${field('email','Correo','','email')}${field('password','Contraseña','','password')}<button class="primary">Entrar</button><p class="muted">Solicita tu cuenta al administrador. La sesión se cierra al recargar por seguridad.</p></form>`);$('#login').onsubmit=async e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));session=await api('/auth/v1/token?grant_type=password','POST',f);profile=(await db('profiles?select=*&id=eq.'+encodeURIComponent(session.user.id)))[0];if(!profile)throw Error('Tu cuenta no tiene acceso al equipo.');$('#account').textContent='Mi cuenta';$('#modal').close();await load();}catch(e){session=null;profile=null;toast(e.message)}};}
$('#account').onclick=login;$('#refresh').onclick=load;$('#search').oninput=()=>{selected=null;resultLimit=12;render()};$('#branch').onchange=basket;
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(b.id==='login-action'){login();return;}if(b.id==='more'){resultLimit+=12;render();return;}if(d.direct){share(false,[d.direct]);return;}if(d.tab){resultLimit=12;tab=d.tab;selected=null;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('selected',x===b));render();}if(d.search){resultLimit=12;$('#search').value=d.search;selected=null;render();}if(d.device){selected=d.device;render();}if(d.add){const s=rows.find(s=>s.service_id===d.add);if(state(s)==='autorizado'&&!cart.includes(d.add)){if(cart.length&&key(rows.find(s=>s.service_id===cart[0]))!==key(s)){if(!confirm('Cambiar de equipo vaciará la cotización actual. ¿Continuar?'))return;cart=[];}const alt=rows.find(x=>cart.includes(x.service_id)&&norm(x.servicio)===norm(s.servicio));if(alt){if(!confirm('Ya seleccionaste otra calidad de este servicio. ¿Reemplazarla?'))return;cart=cart.filter(id=>id!==alt.service_id);}cart.push(d.add);}render();}if(d.remove){cart=cart.filter(id=>id!==d.remove);render();}if(d.edit)edit(rows.find(s=>s.service_id===d.edit));if(d.charge)charge(rows.find(s=>s.service_id===d.charge));if(d.consult)consult(rows.find(s=>s.service_id===d.consult));if(b.id==='new')edit();if(b.id==='back'){selected=null;render();}if(b.id==='request')consult();});
$('#clear').onclick=()=>{cart=[];render()};
async function copyText(t){try{await navigator.clipboard.writeText(t);toast('Mensaje copiado');}catch{modal('<h2>Copia el mensaje</h2><textarea id="manual-copy" rows="10"></textarea>');$('#manual-copy').value=t;$('#manual-copy').select();}}
async function share(whatsapp,onlyIds=null){try{const ids=[...(onlyIds||cart)];if(config.url){await load();}const items=rows.filter(s=>ids.includes(s.service_id));if(items.length!==ids.length)throw Error('El catálogo cambió. Revisa los servicios antes de cotizar.');const message=quote(items,$('#branch').value);if(session)await db('quotes','POST',{user_id:session.user.id,branch:$('#branch').value,message});if(whatsapp){modal('<h2>Compartir cotización</h2><p>Selecciona el contacto en WhatsApp.</p><a id="wa" target="_blank" rel="noopener noreferrer">Abrir WhatsApp</a>');$('#wa').href='https://wa.me/?text='+encodeURIComponent(message);}else await copyText(message);}catch(e){toast(e.message)}}$('#copy').onclick=()=>share(false);$('#whatsapp').onclick=()=>share(true);
function consult(s){const message=`Consulta de precio MovilPhone ${$('#branch').value}: ${s?title(s)+' · '+s.servicio+' · '+s.calidad+' · '+s.variante:$('#search').value}. Favor de confirmar precio instalado, garantía y tiempo.`;modal('<h2>Consultar al responsable</h2><p>Este mensaje no confirma un precio al cliente.</p><textarea id="request-text" rows="5"></textarea><button id="request-copy">Copiar solicitud</button>');$('#request-text').value=message;$('#request-copy').onclick=()=>copyText($('#request-text').value);}
function edit(s){if(profile?.role!=='admin')return;const base=s||rows.find(r=>key(r)===selected)||{};modal(`<h2>${s?'Editar servicio':'Agregar servicio'}</h2><form id="edit"><div class="form-grid">${field('marca','Marca',base.marca)}${field('familia','Familia',base.familia||'', 'text',false)}${field('modelo','Modelo exacto',base.modelo)}${field('categoria','Categoría',base.categoria||'Celular')}${field('servicio','Servicio',s?.servicio)}${field('calidad','Calidad',s?.calidad||'Estándar')}${field('variante','Variante / programación',s?.variante||'','text',false)}${field('precio_publico','Precio público MXN',s?.precio_publico,'number')}${field('garantia','Garantía',s?.garantia)}${field('tiempo_estimado','Tiempo estimado',s?.tiempo_estimado)}${field('ultima_actualizacion','Fecha de validación',s?.ultima_actualizacion?.length===10?s.ultima_actualizacion:'','date',false)}</div><label>Estado<select name="status"><option value="confirmar">Confirmar</option><option value="autorizado">Autorizado</option><option value="diagnostico">Diagnóstico</option></select></label><label>Disponibilidad<select name="active"><option value="true">Activo</option><option value="false">Inactivo (conserva historial)</option></select></label><label>Observaciones<textarea name="observaciones">${esc(s?.observaciones||s?.accion||'')}</textarea></label><button class="primary">Guardar cambios</button><p class="muted">Autorizar requiere precio mayor a cero y fecha válida; vigencia de 90 días. No se modifica por registrar un cobro.</p></form>`);const f=$('#edit');f.elements.status.value=s?.status||'confirmar';f.elements.active.value=String(s?.active!==false);f.onsubmit=e=>{e.preventDefault();saveAction(async()=>{const v=Object.fromEntries(new FormData(f));v.precio_publico=Number(v.precio_publico);v.active=v.active==='true';v.requiere_diagnostico=v.status==='diagnostico';v.service_id=s?.service_id||crypto.randomUUID();v.accion=v.observaciones;if(v.status==='autorizado'&&state(v)!=='autorizado')throw Error('Autorizar requiere precio positivo y fecha válida dentro de 90 días.');const duplicate=rows.find(r=>r.service_id!==v.service_id&&key(r)===key(v)&&norm(r.servicio)===norm(v.servicio)&&norm(r.calidad)===norm(v.calidad)&&norm(r.variante)===norm(v.variante));if(duplicate)throw Error('Ese servicio y variante ya existe. Edita el registro existente.');if(!confirm('¿Guardar estos cambios en el catálogo compartido?'))throw Error('Cambios cancelados');if(s){const result=await db(`services?id=eq.${encodeURIComponent(s.service_id)}&version=eq.${s.version}`,'PATCH',{data:{...s,...v,version:undefined}});if(!result.length)throw Error('Otro usuario modificó el registro. Actualiza antes de editar.');}else await db('services','POST',{id:v.service_id,data:v});});};}
function charge(s){if(!s){toast('Servicio no disponible. Actualiza el catálogo.');return;}modal(`<h2>Registrar trabajo cobrado</h2><p>${esc(title(s))} · ${esc(s.servicio)} · ${esc(s.calidad)}</p><p>Referencia actual: ${money(s.precio_publico||0)}</p><form id="charge"><label>Lugar de atención<select name="branch"><option ${$('#branch').value==='Izamal'?'selected':''}>Izamal</option><option ${$('#branch').value==='Buctzotz'?'selected':''}>Buctzotz</option></select></label>${field('quoted','Precio cotizado real','','number')}${field('paid','Precio cobrado real','','number')}${field('note','Observación','','text',false)}<button class="primary">Guardar cobro</button><p class="muted">No procesa pagos ni cambia el precio oficial.</p></form>`);$('#charge').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));saveAction(()=>db('charges','POST',{id:crypto.randomUUID(),service_id:s.service_id,user_id:session.user.id,branch:v.branch,quoted:Number(v.quoted),paid:Number(v.paid),note:v.note,snapshot:{equipo:title(s),servicio:s.servicio,calidad:s.calidad,precio_oficial:s.precio_publico}}));};}
async function history(){if(!session){$('#results').innerHTML='<div class="empty">Accede para ver el historial compartido.</div>';return;}$('#results').innerHTML='<p>Cargando historial…</p>';try{const [charges,quotes,audit]=await Promise.all([db('charges?order=created_at.desc&limit=200'),db('quotes?order=created_at.desc&limit=30'),profile.role==='admin'?db('audit?order=created_at.desc&limit=30'):Promise.resolve([])]);if(tab!=='historial')return;const stats=new Map();for(const c of charges){let a=stats.get(c.service_id)||[];a.push(c);stats.set(c.service_id,a);}$('#results').innerHTML='<h2>Trabajos cobrados</h2><p class="muted">Hasta 200 cobros recientes visibles según permisos. No equivale al historial completo.</p>'+[...stats.values()].map(a=>`<div class="records"><h3>${esc(a[0].snapshot.equipo)} · ${esc(a[0].snapshot.servicio)}</h3><p>${a.length} cobros · Último ${money(a[0].paid)} · Promedio ${money(a.reduce((n,c)=>n+Number(c.paid),0)/a.length)}<br>Mínimo ${money(Math.min(...a.map(c=>c.paid)))} · Máximo ${money(Math.max(...a.map(c=>c.paid)))}</p>${profile.role==='admin'?`<button data-edit="${esc(a[0].service_id)}">Revisar precio oficial</button>`:''}</div>`).join('')+charges.map(c=>`<div class="records">${esc(c.created_at)} · ${esc(c.branch)}<p>${esc(c.snapshot.equipo)} · ${esc(c.snapshot.servicio)}<br>Cotizado ${money(c.quoted)} → Cobrado ${money(c.paid)}</p><small>Colaborador: ${esc(c.user_id)}</small><p>${esc(c.note)}</p></div>`).join('')+'<h2>Cotizaciones recientes</h2>'+quotes.map(q=>`<div class="records"><small>${esc(q.created_at)} · ${esc(q.branch)}</small><pre>${esc(q.message)}</pre></div>`).join('')+(profile.role==='admin'?'<h2>Auditoría de precios</h2>'+audit.map(a=>`<details class="records"><summary>${esc(a.created_at)} · ${esc(a.service_id)} · ${esc(a.actor||'Importación')}</summary><pre>${esc(JSON.stringify({antes:a.before,despues:a.after},null,2))}</pre></details>`).join(''):'');}catch(e){$('#results').textContent=e.message;}}
load();
