import {groups,score,serviceIntent,state,money} from './core.js';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function serviceHTML(s,{admin=false,signedIn=false,cart=[]}={}){
 const st=state(s),active=s.active!==false,allowed=st==='autorizado'&&active,id=esc(s.service_id),hasPrice=typeof s.precio_publico==='number'&&s.precio_publico>0;
 const label=!active?'Inactivo':st==='autorizado'?'Precio autorizado':st==='diagnostico'?'Requiere diagnóstico':'Precio registrado · confirmar';
 const from=st==='diagnostico'&&/desde/i.test(s.tipo_cotizacion||'');
 return `<article class="service-row" data-record="${id}"><div class="service-name"><h3>${esc(s.servicio)}</h3><p>${esc(s.calidad||'Calidad por confirmar')}${s.variante?' · '+esc(s.variante):''}</p></div><div class="service-price"><strong>${hasPrice?(from?'<small>Desde </small>':'')+money(s.precio_publico):'Consultar precio'}</strong><span class="tag ${st}">${label}</span></div><div class="service-actions">${allowed?`<button class="primary" data-direct="${id}">Copiar cotización</button><button class="add" data-add="${id}" aria-label="Agregar ${esc(s.servicio)} a cotización">${cart.includes(s.service_id)?'✓ Agregado':'+ Combinar'}</button>`:`<button data-consult="${id}">Consultar precio</button>${admin?`<button class="plain" data-edit="${id}">Validar / editar</button>`:''}`}</div><details class="service-detail"><summary>Garantía, tiempo y más opciones</summary><div class="detail-content"><dl><div><dt>Garantía</dt><dd>${esc(s.garantia||'Por confirmar')}</dd></div><div><dt>Tiempo estimado</dt><dd>${esc(s.tiempo_estimado||'Por confirmar')}</dd></div><div><dt>Última actualización</dt><dd>${esc(s.ultima_actualizacion||'Sin fecha')}</dd></div></dl><p>${esc(s.observaciones||s.accion||'')}</p>${!allowed&&hasPrice?'<p>Referencia interna: confirma antes de prometer este importe al cliente.</p>':''}<div class="detail-buttons">${signedIn?`<button data-charge="${id}">Registrar cobro</button>`:''}${admin?`<button data-edit="${id}">Editar servicio general</button>`:''}</div></div></details></article>`;
}
export function resultsHTML(rows,{query='',selected=null,tab='cotizar',admin=false,signedIn=false,cart=[],limit=12}={}){
const opts={admin,signedIn,cart};let gs=groups(rows,selected?'':query,tab==='admin');if(tab==='pendientes')gs=gs.map(g=>({...g,services:g.services.filter(s=>state(s)!=='autorizado')})).filter(g=>g.services.length);
if(selected)gs=gs.filter(g=>g.key===selected);
else if(serviceIntent(query))gs=gs.map(g=>({...g,services:g.services.filter(s=>score(s,query)>0)})).filter(g=>g.services.length);
const total=gs.length;gs=gs.slice(0,limit);
return (tab==='admin'?'<div class="toolbar"><button id="new" class="primary">+ Agregar servicio general</button><span>Los cambios se aplican a todo MovilPhone.</span></div>':'')+(selected?'<button id="back" class="plain">← Volver a resultados</button>':'')+`<div class="result-heading"><h2>${selected?'Servicios del equipo':query?'Resultados de búsqueda':'Catálogo de servicios'}</h2><span>${total} equipos · precios MXN</span></div>`+
gs.map(g=>`<section class="device-group"><div class="device-heading"><h2>${esc(g.title)}</h2><div>${selected?(admin?'<button id="new" class="plain">+ Agregar servicio</button>':''):`<button class="plain" data-device="${esc(g.key)}">Ver todos los servicios →</button>`}</div></div>${g.services.map(s=>serviceHTML(s,opts)).join('')}</section>`).join('')+(total>limit?'<button id="more" class="load-more">Mostrar más resultados</button>':'')+(total?'':'<div class="empty"><h2>No encontramos ese servicio</h2><p>Prueba con la marca y el modelo exacto, o busca solamente el equipo.</p><button id="request">Solicitar precio faltante</button></div>');
}
